#!/usr/bin/env bash
# V1-W0.1 workspace-unstage-plan.sh — REVIEW ONLY. Do not auto-execute.
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"

# === commit1 unstage ===
git restore --staged -- GMRobot/deploy/ai_server/perception_service.py
git restore --staged -- GMRobot/deploy/ai_server/vlm_service.py
git restore --staged -- GMRobot/source/GMRobot/GMRobot/perception/__init__.py
git restore --staged -- GMRobot/source/GMRobot/GMRobot/perception/backends.py
git restore --staged -- GMRobot/source/GMRobot/GMRobot/perception/client.py
git restore --staged -- GMRobot/source/GMRobot/GMRobot/perception/legacy_gateway.py
git restore --staged -- GMRobot/source/GMRobot/GMRobot/perception/schema.py
git restore --staged -- GMRobot/source/GMRobot/GMRobot/vlm/__init__.py
git restore --staged -- GMRobot/source/GMRobot/GMRobot/vlm/client.py
git restore --staged -- GMRobot/source/GMRobot/GMRobot/vlm/legacy_gateway.py
git restore --staged -- GMRobot/source/GMRobot/GMRobot/vlm/schema.py
git restore --staged -- GMRobot/source/GMRobot/GMRobot/vlm/service_handlers.py

# === commit2 unstage ===
git restore --staged -- GMRobot/source/GMRobot/GMRobot/shadow/__init__.py
git restore --staged -- GMRobot/source/GMRobot/GMRobot/shadow/config_resolve.py
git restore --staged -- GMRobot/source/GMRobot/GMRobot/shadow/control_isolation.py
git restore --staged -- GMRobot/source/GMRobot/GMRobot/shadow/five_stage_worker.py
git restore --staged -- GMRobot/source/GMRobot/GMRobot/shadow/isolation.py
git restore --staged -- GMRobot/source/GMRobot/GMRobot/shadow/logger.py
git restore --staged -- GMRobot/source/GMRobot/GMRobot/shadow/scheduler.py

# === commit3 unstage ===
git restore --staged -- GMRobot/scripts/gm_state_machine_agent.py
git restore --staged -- GMRobot/scripts/replay_semantic_supervisor_v1b.py
git restore --staged -- GMRobot/scripts/test_canonical_package_import_v1c0p1_unit.py
git restore --staged -- GMRobot/scripts/test_semantic_supervisor_logger_unit.py
git restore --staged -- GMRobot/scripts/test_semantic_supervisor_replay_unit.py
git restore --staged -- GMRobot/scripts/test_semantic_supervisor_shadow_v1c0_unit.py
git restore --staged -- GMRobot/scripts/test_semantic_supervisor_state_unit.py
git restore --staged -- GMRobot/scripts/test_semantic_supervisor_unit.py
git restore --staged -- GMRobot/source/GMRobot/GMRobot/__init__.py
git restore --staged -- GMRobot/source/GMRobot/GMRobot/safety/semantic_supervisor.py
git restore --staged -- GMRobot/source/GMRobot/GMRobot/safety/semantic_supervisor_logger.py
git restore --staged -- GMRobot/source/GMRobot/GMRobot/shadow/semantic_bridge.py

# === commit4 unstage ===
git restore --staged -- GMRobot/configs/five_stage_shadow_temporal_v2.yaml
git restore --staged -- GMRobot/configs/vlm_client_legacy_gateway_temporal_v2.yaml
git restore --staged -- GMRobot/scripts/fixtures/v1d2a/d1bs_step100_static.json
git restore --staged -- GMRobot/scripts/fixtures/v1d2a/d1bs_step200_static.json
git restore --staged -- GMRobot/scripts/fixtures/v1d2a/p1_frame0_static.json
git restore --staged -- GMRobot/scripts/fixtures/v1d2a/p1_frame1_static.json
git restore --staged -- GMRobot/scripts/fixtures/v1d2a/synthetic_dynamic_native.json
git restore --staged -- GMRobot/scripts/fixtures/v1d2a/synthetic_entity_mismatch_vlm.json
git restore --staged -- GMRobot/scripts/fixtures/v1d2a/synthetic_functional_native.json
git restore --staged -- GMRobot/scripts/fixtures/v1d2a/synthetic_high_speed_low_vlm_conf.json
git restore --staged -- GMRobot/scripts/fixtures/v1d2a/synthetic_high_vlm_stationary_track.json
git restore --staged -- GMRobot/scripts/fixtures/v1d2a/synthetic_static_highconf_for_temporal.json
git restore --staged -- GMRobot/scripts/fixtures/v1d2a/task_place_b_occupied.json
git restore --staged -- GMRobot/scripts/fixtures/v1d2a/track_hand_for_mismatch.json
git restore --staged -- GMRobot/scripts/fixtures/v1d2a/track_lost.json
git restore --staged -- GMRobot/scripts/fixtures/v1d2a/track_stationary.json
git restore --staged -- GMRobot/scripts/fixtures/v1d2a/track_valid_hand_moving.json
git restore --staged -- GMRobot/scripts/fixtures/v1d2a/v0c3_frame0_static.json
git restore --staged -- GMRobot/scripts/fixtures/v1d2a/v0c3_frame1_dynamic_lowconf.json
git restore --staged -- GMRobot/scripts/test_v1d2a_temporal_fusion_unit.py
git restore --staged -- GMRobot/source/GMRobot/GMRobot/safety/semantic_key_v2.py
git restore --staged -- GMRobot/source/GMRobot/GMRobot/safety/semantic_temporal_fusion.py
git restore --staged -- GMRobot/source/GMRobot/GMRobot/vlm/prompt_v2.py
git restore --staged -- GMRobot/source/GMRobot/GMRobot/vlm/task_context.py
git restore --staged -- GMRobot/source/GMRobot/GMRobot/vlm/temporal_evidence.py
git restore --staged -- GMRobot/source/GMRobot/GMRobot/vlm/versions.py

# === commit5 unstage ===
git restore --staged -- GMRobot/configs/five_stage_shadow.yaml
git restore --staged -- GMRobot/configs/five_stage_shadow_legacy_gateway.yaml
git restore --staged -- GMRobot/configs/five_stage_shadow_legacy_gateway_v0c.yaml
git restore --staged -- GMRobot/configs/five_stage_shadow_legacy_gateway_v0c2.yaml
git restore --staged -- GMRobot/configs/five_stage_shadow_legacy_gateway_v0c3.yaml
git restore --staged -- GMRobot/configs/five_stage_shadow_legacy_gateway_v1c1.yaml
git restore --staged -- GMRobot/configs/five_stage_shadow_legacy_gateway_v1c1r.yaml
git restore --staged -- GMRobot/configs/five_stage_shadow_legacy_gateway_v1c1r_p1.yaml
git restore --staged -- GMRobot/configs/ivj_v1d1_far_corridor_motion.yaml
git restore --staged -- GMRobot/configs/ivj_v1d1b_functional_blockage.yaml
git restore --staged -- GMRobot/configs/perception_client.yaml
git restore --staged -- GMRobot/configs/perception_client_legacy_gateway.yaml
git restore --staged -- GMRobot/configs/semantic_safety_supervisor.yaml
git restore --staged -- GMRobot/configs/semantic_safety_supervisor_shadow_live.yaml
git restore --staged -- GMRobot/configs/semantic_safety_supervisor_shadow_v1c1.yaml
git restore --staged -- GMRobot/configs/semantic_safety_supervisor_shadow_v1c1r.yaml
git restore --staged -- GMRobot/configs/semantic_safety_supervisor_shadow_v1c1r_p1.yaml
git restore --staged -- GMRobot/configs/semantic_safety_supervisor_temporal_v2.yaml
git restore --staged -- GMRobot/configs/vlm_client.yaml
git restore --staged -- GMRobot/configs/vlm_client_legacy_gateway.yaml
git restore --staged -- GMRobot/scripts/build_v1d1a_capture_manifest.py
git restore --staged -- GMRobot/scripts/build_v1d1b_capture_manifest.py
git restore --staged -- GMRobot/scripts/fixtures/v0b3_legacy/legacy_ground_response.json
git restore --staged -- GMRobot/scripts/fixtures/v0b3_legacy/legacy_track_init_response.json
git restore --staged -- GMRobot/scripts/fixtures/v0b3_legacy/legacy_track_step_response.json
git restore --staged -- GMRobot/scripts/fixtures/v0b3_legacy/legacy_vlm_analyze_response.json
git restore --staged -- GMRobot/scripts/fixtures/v0b3_legacy/legacy_vlm_missing_consequence.json
git restore --staged -- GMRobot/scripts/probe_v0b2b_legacy_endpoint.py
git restore --staged -- GMRobot/scripts/probe_v0b2b_track_step_continuation.py
git restore --staged -- GMRobot/scripts/run_v0b4_legacy_gateway_replay.py
git restore --staged -- GMRobot/scripts/test_five_stage_legacy_gateway_pipeline_unit.py
git restore --staged -- GMRobot/scripts/test_five_stage_pipeline_halt_unit.py
git restore --staged -- GMRobot/scripts/test_five_stage_shadow_isolation_unit.py
git restore --staged -- GMRobot/scripts/test_five_stage_shadow_logging_unit.py
git restore --staged -- GMRobot/scripts/test_five_stage_shadow_scheduler_unit.py
git restore --staged -- GMRobot/scripts/test_five_stage_shadow_worker_unit.py
git restore --staged -- GMRobot/scripts/test_five_stage_shutdown_drain_unit.py
git restore --staged -- GMRobot/scripts/test_five_stage_stale_unique_count_unit.py
git restore --staged -- GMRobot/scripts/test_perception_legacy_gateway_unit.py
git restore --staged -- GMRobot/scripts/test_perception_service_contract_unit.py
git restore --staged -- GMRobot/scripts/test_session_continuity_unit.py
git restore --staged -- GMRobot/scripts/test_shadow_config_resolve_unit.py
git restore --staged -- GMRobot/scripts/test_v0b2b_probe_limiter_unit.py
git restore --staged -- GMRobot/scripts/test_v0b2b_track_step_continuation_unit.py
git restore --staged -- GMRobot/scripts/test_v0b4_replay_validator_unit.py
git restore --staged -- GMRobot/scripts/test_v1d1a_far_corridor_capture_unit.py
git restore --staged -- GMRobot/scripts/test_v1d1b_functional_blockage_capture_unit.py
git restore --staged -- GMRobot/scripts/test_vlm_legacy_gateway_unit.py
git restore --staged -- GMRobot/scripts/test_vlm_schema_unit.py
git restore --staged -- GMRobot/scripts/test_vlm_service_contract_unit.py
git restore --staged -- GMRobot/source/GMRobot/GMRobot/shadow/v1d1a_capture.py
git restore --staged -- GMRobot/source/GMRobot/GMRobot/shadow/v1d1b_capture.py
git restore --staged -- GMRobot/source/GMRobot/GMRobot/tasks/manager_based/gmrobot/gmrobot_env_cfg.py

# === commit6 unstage ===
git restore --staged -- g1_ur10e_disturbance/docker/image_meta/five-stage-shadow-v0c-20260721.txt
git restore --staged -- g1_ur10e_disturbance/docker/image_meta/five-stage-shadow-v0c1-20260721.txt
git restore --staged -- g1_ur10e_disturbance/docker/image_meta/five-stage-shadow-v0c2-20260721.txt
git restore --staged -- g1_ur10e_disturbance/docker/image_meta/five-stage-shadow-v0c3-20260721.txt
git restore --staged -- g1_ur10e_disturbance/docker/image_meta/semantic-shadow-v1c0-20260722.txt
git restore --staged -- g1_ur10e_disturbance/docker/image_meta/semantic-shadow-v1c0p1-20260722.txt
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/paper-demo-vlm-workspace-status-2026-07-22.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/paper-demo-vlm-workspace-status-2026-07-22.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/paper-evidence-index-2026-07-22.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-five-stage-audit-machine-2026-07-21.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-five-stage-readonly-audit-2026-07-21.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-five-stage-v0a-implementation-2026-07-21.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-five-stage-v0a-status-2026-07-21.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v0b1-rgb-capture-preflight-2026-07-21.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v0b1-rgb-capture-result-2026-07-21.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v0b2a-endpoint-preflight-2026-07-21.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v0b2a-endpoint-preflight-retry1-2026-07-21.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v0b2b-legacy-capability-probe-2026-07-21.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v0b2b-track-step-continuation-2026-07-21.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v0b3-legacy-gateway-implementation-2026-07-21.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v0b3-legacy-gateway-status-2026-07-21.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v0b4-legacy-gateway-replay-2026-07-21.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v0b4-legacy-gateway-status-2026-07-21.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v0c0-image-build-smoke-2026-07-21.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v0c0-image-status-2026-07-21.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v0c1-isaac-shadow-result-2026-07-21.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v0c1-isaac-shadow-status-2026-07-21.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v0c1-shutdown-drain-fix-2026-07-21.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v0c1-shutdown-drain-status-2026-07-21.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v0c2-isaac-shadow-result-2026-07-21.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v0c2-isaac-shadow-status-2026-07-21.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v0c2-session-continuity-fix-2026-07-21.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v0c2-session-continuity-status-2026-07-21.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v0c3-isaac-shadow-result-2026-07-21.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v0c3-isaac-shadow-status-2026-07-21.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1b-semantic-supervisor-implementation-2026-07-21.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1b-semantic-supervisor-status-2026-07-21.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1c0-semantic-shadow-status-2026-07-22.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1c0-semantic-shadow-wiring-2026-07-22.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1c1-gpu-failure-audit-2026-07-22.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1c1-gpu-failure-audit-2026-07-22.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1c1-isaac-semantic-shadow-result-2026-07-22.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1c1-isaac-semantic-shadow-run-2026-07-22.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1c1-isaac-semantic-shadow-run-status-2026-07-22.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1c1-isaac-semantic-shadow-status-2026-07-22.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1c1r-canonical-import-fix-2026-07-22.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1c1r-canonical-import-fix-2026-07-22.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1c1r-isaac-semantic-shadow-result-2026-07-22.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1c1r-isaac-semantic-shadow-status-2026-07-22.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1c1r-p1-isaac-semantic-shadow-result-2026-07-22.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1c1r-p1-isaac-semantic-shadow-status-2026-07-22.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1c1r-perception-warming-audit-2026-07-22.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1c1r-perception-warming-audit-2026-07-22.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1c1r-preflight-2026-07-22.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1c1r-preflight-2026-07-22.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1d0-positive-shadow-design-2026-07-22.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1d0-positive-shadow-design-2026-07-22.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1d1a-positive-scene-capture-2026-07-22.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1d1a-positive-scene-capture-2026-07-22.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1d1b-functional-blockage-capture-2026-07-22.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1d1b-functional-blockage-capture-2026-07-22.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1d1b-vlm-semantic-screen-2026-07-22.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1d1b-vlm-semantic-screen-2026-07-22.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1d2-semantic-interface-audit-2026-07-22.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1d2-semantic-interface-audit-2026-07-22.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1d2a-temporal-fusion-implementation-2026-07-22.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1d2a-temporal-fusion-implementation-2026-07-22.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1d2b-task-context-replay-2026-07-22.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1d2b-task-context-replay-2026-07-22.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1e0-semantic-evaluation-design-2026-07-22.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1e0-semantic-evaluation-design-2026-07-22.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1e01-positive-dataset-acquisition-plan-2026-07-22.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/vlm-v1e01-positive-dataset-acquisition-plan-2026-07-22.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/workspace-audit-2026-07-22/c6-markdown-hard-break-allowlist.txt
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/workspace-audit-2026-07-22/classification-summary.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/workspace-audit-2026-07-22/consistency-check-report.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/workspace-audit-2026-07-22/duplicate-name-candidates.txt
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/workspace-audit-2026-07-22/file-ownership-anomalies.txt
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/workspace-audit-2026-07-22/git-status-porcelain.txt
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/workspace-audit-2026-07-22/ignored-evidence-roots.txt
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/workspace-audit-2026-07-22/large-files.txt
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/workspace-audit-2026-07-22/offline-test-log.txt
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/workspace-audit-2026-07-22/proposed-commit-groups.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/workspace-audit-2026-07-22/sensitive-scan-report.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/workspace-audit-2026-07-22/sensitive-scan-report.txt
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/workspace-audit-2026-07-22/snapshot-meta.txt
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/workspace-audit-2026-07-22/tracked-diff-name-status.txt
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/workspace-audit-2026-07-22/tracked-diff-stat.txt
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/workspace-audit-2026-07-22/untracked-files.txt
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/workspace-audit-2026-07-22/workspace-file-classification.jsonl
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/workspace-cleanup-report-2026-07-22.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/workspace-cleanup-report-2026-07-22.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/workspace-commit-report-2026-07-22.json
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/workspace-commit-report-2026-07-22.md
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/workspace-file-classification.jsonl
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/workspace-stage-plan.sh
git restore --staged -- g1_ur10e_disturbance/docs/cross-project/workspace-unstage-plan.sh
