"""E01-Func-C target-container-full override (pure; no Isaac import).

Default Dual/GMRobot box_B remains ``container.usd``. Opt-in:

  GMROBOT_V1E01_TARGET_FULL=1

Visual-only capture mode (explicit opt-in, default off):

  GMROBOT_V1E01_VISUAL_ONLY=1

When enabled, only ``box_B`` switches to ``container_full.usd`` with a
Func-C-specific spawn scale (the full USD already embeds cm→m hierarchy
and ``metersPerUnit=1``; applying the empty-box ``0.01`` scale would shrink
it ~100×).

Does not enable D1B ``GMROBOT_V1D1B_FUNCTIONAL_BLOCK`` / part_5000@B@10.
"""

from __future__ import annotations

import hashlib
import os
from pathlib import Path
from typing import Mapping

CONTAINER_USD_NAME = "container.usd"
CONTAINER_FULL_USD_NAME = "container_full.usd"
# Spawn payload: relative defaultPrim, no /World absolute paths, no physics.
# Semantic distinction source-of-truth remains container_full.usd.
CONTAINER_FULL_SPAWN_USD_NAME = "container_full_visual.usd"
CONTAINER_FULL_CONTENT_SPAWN_USD_NAME = "container_full_content_visual.usd"

# Normalized derivatives (single RigidBodyAPI, no nesting).
# Generated by GMRobot/scripts/normalize_container_usd.py and normalize_part_usd.py.
# Retained for compatibility tests but NOT used for Func-C source box A.
CONTAINER_FIXED_USD_NAME = "container_fixed.usd"
PART_FIXED_USD_NAME = "part/part_fixed.usd"
PART_USD_NAME = "part/part_5000.usd"

# Empty box uses (0.01,)*3 in gmrobot_env_cfg. Full visual USD is already meters.
CONTAINER_FULL_SCALE: tuple[float, float, float] = (1.0, 1.0, 1.0)

SCENE_GROUP = "e01_func_c"
EXPECTED_RISK_TYPE = "functional"
LABEL_STATUS = "provisional"
REVIEWER_APPROVED = False
MOTION_SOURCE = "none_static_functional_scene"
E01_FUNC_C_SEED = 51
E01_FUNC_C_CAPTURE_STEPS: tuple[int, ...] = (100, 200)
E01_FUNC_C_GEOMETRY_WINDOW: tuple[int, int] = (100, 200)
CAMERA_POS: tuple[float, float, float] = (0.35, 0.0, 2.5)
CAMERA_ROT: tuple[float, float, float, float] = (0.7071, 0.0, 0.7071, 0.0)
MIN_TARGET_ROI_PX2: float = 2500.0

# Dyn-B reference-locked source-container identity (left green empty box).
SOURCE_VISUAL_ASSET_NAME = CONTAINER_USD_NAME
SOURCE_VISUAL_ASSET_SHA256 = "ee307082665bb316eb53965861f8ca635a8e922aa8f90805126faf9cc75493a9"
SOURCE_VISUAL_MATERIAL_PATH = "/Root/Container/Ref/Looks/DefaultMaterial"
SOURCE_VISUAL_PRIM_PATH = "{ENV_REGEX_NS}/ContainerA"
SOURCE_VISUAL_DEFAULT_PRIM = "/Root"
SOURCE_VISUAL_SCALE: tuple[float, float, float] = (0.01, 0.01, 0.01)
SOURCE_VISUAL_ORIENTATION_QUAT_WXYZ: tuple[float, float, float, float] = (0.5, 0.5, 0.5, 0.5)


def _truthy(raw: str | None) -> bool:
    return str(raw or "").strip().lower() in {"1", "true", "yes", "on"}


def target_full_enabled(env: Mapping[str, str] | None = None) -> bool:
    e = os.environ if env is None else env
    return _truthy(e.get("GMROBOT_V1E01_TARGET_FULL"))


def visual_only_enabled(env: Mapping[str, str] | None = None) -> bool:
    e = os.environ if env is None else env
    return _truthy(e.get("GMROBOT_V1E01_VISUAL_ONLY"))


def d1b_blocker_enabled(env: Mapping[str, str] | None = None) -> bool:
    e = os.environ if env is None else env
    return _truthy(e.get("GMROBOT_V1D1B_FUNCTIONAL_BLOCK"))


def resolve_box_usd_name(
    container_name: str,
    *,
    env: Mapping[str, str] | None = None,
) -> str:
    """Return USD basename for box_A / box_B (spawn path)."""
    name = str(container_name)
    if name == "B" and target_full_enabled(env) and not visual_only_enabled(env):
        return CONTAINER_FULL_SPAWN_USD_NAME
    if name == "A" and target_full_enabled(env):
        return SOURCE_VISUAL_ASSET_NAME
    return CONTAINER_USD_NAME


def target_full_visual_composition_enabled(env: Mapping[str, str] | None = None) -> bool:
    """True when Func-C target-full uses canonical shell + content-only overlay."""
    return bool(target_full_enabled(env) and visual_only_enabled(env))


def resolve_box_b_content_overlay_usd_name(
    *,
    env: Mapping[str, str] | None = None,
) -> str | None:
    """Return content-only overlay USD basename for box_B if enabled."""
    if target_full_visual_composition_enabled(env):
        return CONTAINER_FULL_CONTENT_SPAWN_USD_NAME
    return None


def resolve_box_source_usd_name(
    container_name: str,
    *,
    env: Mapping[str, str] | None = None,
) -> str:
    """Semantic source asset name (for manifests / precheck)."""
    name = str(container_name)
    if name == "B" and target_full_enabled(env):
        return CONTAINER_FULL_USD_NAME
    return CONTAINER_USD_NAME


def resolve_box_scale(
    container_name: str,
    *,
    default_scale: tuple[float, float, float],
    env: Mapping[str, str] | None = None,
) -> tuple[float, float, float]:
    if str(container_name) == "B" and target_full_enabled(env):
        return CONTAINER_FULL_SCALE
    return tuple(float(x) for x in default_scale)


def resolve_part_usd_name(
    *,
    env: Mapping[str, str] | None = None,
) -> str:
    """Return USD basename for part spawn. Uses fixed (non-nested) asset in Func-C mode."""
    if target_full_enabled(env):
        return PART_FIXED_USD_NAME
    return PART_USD_NAME


def resolve_v1e01_mode_flags(env: Mapping[str, str] | None = None) -> dict[str, object]:
    """Resolve explicit mode flags for Func-C capture/runtime gating."""
    visual_only = visual_only_enabled(env)
    target_full = target_full_enabled(env)
    d1b_blocker = d1b_blocker_enabled(env)
    gate_ok = (not visual_only) or (target_full and not d1b_blocker)
    reasons: list[str] = []
    if visual_only and not target_full:
        reasons.append("visual_only_requires_target_full")
    if visual_only and d1b_blocker:
        reasons.append("visual_only_forbids_d1b_blocker")
    return {
        "target_full_enabled": bool(target_full),
        "visual_only_enabled": bool(visual_only),
        "d1b_blocker_enabled": bool(d1b_blocker),
        "task_execution": False if visual_only else True,
        "visual_dataset_only": True if visual_only else False,
        "spawn_task_parts": False if visual_only else True,
        "gate_ok": bool(gate_ok),
        "gate_reasons": reasons,
    }


def assert_v1e01_mode_gate(env: Mapping[str, str] | None = None) -> None:
    flags = resolve_v1e01_mode_flags(env)
    if not bool(flags["gate_ok"]):
        raise RuntimeError(
            "Invalid V1E01 mode gate: "
            + ",".join(str(x) for x in flags.get("gate_reasons", []))
        )


def assets_dir_from_env_cfg_file(env_cfg_path: Path | str) -> Path:
    p = Path(env_cfg_path).resolve()
    # .../GMRobot/tasks/manager_based/gmrobot/gmrobot_env_cfg.py
    # assets at .../GMRobot/assets
    return (p.parents[3] / "assets").resolve()


def source_visual_contract(assets_dir: Path | str) -> dict[str, object]:
    """Return static identity contract for Func-C source container visual."""
    root = Path(assets_dir)
    source_asset = root / SOURCE_VISUAL_ASSET_NAME
    sha = hashlib.sha256(source_asset.read_bytes()).hexdigest() if source_asset.is_file() else ""
    return {
        "source_visual_asset_name": SOURCE_VISUAL_ASSET_NAME,
        "source_visual_asset_path": str(source_asset),
        "source_visual_asset_sha256": sha,
        "source_visual_asset_sha256_expected": SOURCE_VISUAL_ASSET_SHA256,
        "source_visual_material_path": SOURCE_VISUAL_MATERIAL_PATH,
        "source_visual_default_prim": SOURCE_VISUAL_DEFAULT_PRIM,
        "source_visual_prim_path": SOURCE_VISUAL_PRIM_PATH,
        "source_visual_scale": list(SOURCE_VISUAL_SCALE),
        "source_visual_orientation_quat_wxyz": list(SOURCE_VISUAL_ORIENTATION_QUAT_WXYZ),
        "matches_dyn_b_reference": bool(sha == SOURCE_VISUAL_ASSET_SHA256),
    }
